#!/usr/bin/env bash
SESS=home
CAP="--cap-add SYS_ADMIN --cap-add NET_ADMIN --cap-add MKNOD"
PWD=$(pwd)
tmux kill-session -t $SESS 2>/dev/null
tmux new-session -s $SESS -d
tmux rename-window -t $SESS:0 "admin"
tmux new-window -t $SESS -n "sensor"
tmux new-window -t $SESS -n "action"
tmux split-window -t $SESS:"sensor"

# home_nlp
tmux send-keys -t $SESS:"sensor".0 "# Setting up NLP environment..." C-m
tmux send-keys -t $SESS:"sensor".0 "mkdir -p venvs" C-m
tmux send-keys -t $SESS:"sensor".0 "if [ ! -d 'venvs/home_nlp' ]; then python3 -m venv venvs/home_nlp --system-site-packages; fi" C-m
tmux send-keys -t $SESS:"sensor".0 ". venvs/home_nlp/bin/activate" C-m
tmux send-keys -t $SESS:"sensor".0 "python3 -m pip install -r src/home_nlp/requirements.txt" C-m
tmux send-keys -t $SESS:"sensor".0 "python3 -m colcon build --symlink-install --event-handlers console_cohesion+ --base-paths src --packages-select home_nlp" C-m
tmux send-keys -t $SESS:"sensor".0 "ros2 launch home_nlp launch.py" C-m

# yolo_ros
tmux send-keys -t $SESS:"sensor".1 "echo 'YOLO Pane'" C-m

tmux select-window -t $SESS:"sensor"
tmux attach -t $SESS
