SESS=home
PWD=$(pwd)

kill-session -t $SESS
new-session -s $SESS -d
rename-window -t $SESS:0 "admin"
new-window -t $SESS -n "sensor"
new-window -t $SESS -n "action"
split-window -t $SESS:"sensor"

# home_nlp
send-keys -t $SESS:"sensor".0 "# Setting up NLP environment..." C-m
send-keys -t $SESS:"sensor".0 "mkdir -p venvs" C-m
send-keys -t $SESS:"sensor".0 "if [ ! -d 'venvs/home_nlp' ]; then python3 -m venv venvs/home_nlp --system-site-packages; fi" C-m
send-keys -t $SESS:"sensor".0 ". venvs/home_nlp/bin/activate" C-m
send-keys -t $SESS:"sensor".0 "python3 -m pip install -r src/home_nlp/requirements.txt" C-m
send-keys -t $SESS:"sensor".0 "python3 -m colcon build --symlink-install --event-handlers console_cohesion+ --base-paths src --packages-select home_nlp" C-m
send-keys -t $SESS:"sensor".0 "ros2 launch home_nlp launch.py" C-m

# yolo_ros
send-keys -t $SESS:"sensor".1 "echo 'YOLO Pane'" C-m

select-window -t $SESS:"sensor"
attach -t $SESS
